version: '3.2'

services:
  portainer:
    image: portainer/portainer-ce:2.9.2
    restart: always
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/fitneks/portainer/${ENV_NAME}/data:/data
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true