version: "3.6"
services:
  nginx:
    restart: always
    build: ./
    volumes:
      - ${BS_ROOT_DIR}/nginx/conf.d/:/etc/nginx/conf.d/
      - ${BS_ROOT_DIR}/nginx/certificates/:/etc/nginx/certificates/
      - ${BS_ROOT_DIR}/nginx/letsencrypt/:/etc/letsencrypt/
      - ${BS_ROOT_DIR}/nginx/letsencrypt-lib:/var/lib/letsencrypt
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-network
networks:
  nginx-network:
    external: false
    name: nginx-network